Fix gdm login script

diff --git a/profiles/templates/3.1/5_ac_desktop_install/up/gdm-3/PostLogin/Default b/profiles/templates/3.1/5_ac_desktop_install/up/gdm-3/PostLogin/Default
--- a/profiles/templates/3.1/5_ac_desktop_install/up/gdm-3/PostLogin/Default
+++ b/profiles/templates/3.1/5_ac_desktop_install/up/gdm-3/PostLogin/Default
@@ -1,4 +1,9 @@
 # Calculate append=replace chmod=755 force
 #!/bin/bash
 
-/usr/share/calculate/xdm/xdm --login || kill $PPID
+rm -f /tmp/$USER-login-status
+if ! /usr/share/calculate/xdm/xdm --login
+then
+    echo "ERROR" >>/tmp/$USER-login-status
+    chown ${USER}. /tmp/$USER-login-status
+fi
