sys-apps/calculate-toolkit: fix ebuild

diff --git a/sys-apps/calculate-toolkit/files/calculate-toolkit-0.3.2-20230215.patch b/sys-apps/calculate-toolkit/files/calculate-toolkit-0.3.2-20230215.patch
--- a/sys-apps/calculate-toolkit/files/calculate-toolkit-0.3.2-20230215.patch
+++ b/sys-apps/calculate-toolkit/files/calculate-toolkit-0.3.2-20230215.patch
@@ -1,5 +1,5 @@
 diff --git a/cl-lxc b/cl-lxc
-index 9d5fc69..84cbc24 100755
+index 3f6b3bc..9ca17dc 100644
 --- a/cl-lxc
 +++ b/cl-lxc
 @@ -19,8 +19,7 @@ set -ueo pipefail
@@ -32,7 +32,17 @@ index 9d5fc69..84cbc24 100755
  			echo $"Parameter '$1' contains no value!" >&2
  			exit 1
  		fi
-@@ -111,8 +108,7 @@ get_args(){
+@@ -69,8 +66,7 @@ get_args(){
+ 	diff_=0
+ 	clear_=0
+ 	mirror_=mirror.calculate-linux.org
+-	while (( $# > 0 ))
+-	do
++	while (( $# > 0 )); do
+ 		case "$1" in
+ 		-P|--profile)
+ 			check_val $@
+@@ -111,8 +107,7 @@ get_args(){
  			break
  			;;
  		*)
@@ -42,7 +52,7 @@ index 9d5fc69..84cbc24 100755
  				break
  			fi
  			printf $"Invalid option '%s'.\n" $1 >&2
-@@ -121,20 +117,16 @@ get_args(){
+@@ -121,20 +116,16 @@ get_args(){
  		esac
  		shift
  	done
@@ -67,7 +77,7 @@ index 9d5fc69..84cbc24 100755
  			echo $"The name '$lxc_' is reserved. Use a different container name." >&2
  			exit 1
  		fi
-@@ -148,13 +140,13 @@ get_args(){
+@@ -148,13 +139,13 @@ get_args(){
  
  print_profile(){
  	local profile_dir
@@ -85,7 +95,7 @@ index 9d5fc69..84cbc24 100755
  			git clone https://github.com/calculatelinux/container $profile_dir &>/dev/null
  		else
  			git -C $profile_dir pull &>/dev/null
-@@ -162,14 +154,12 @@ print_profile(){
+@@ -162,14 +153,12 @@ print_profile(){
  	fi
  
  	# Отобразим список доступных профилей или проверим наличие запрошенного
@@ -102,7 +112,7 @@ index 9d5fc69..84cbc24 100755
  			return 1
  		fi
  	fi
-@@ -185,8 +175,7 @@ set_vars(){
+@@ -185,8 +174,7 @@ set_vars(){
  		exit 1
  	)
  
@@ -112,7 +122,7 @@ index 9d5fc69..84cbc24 100755
  		name_lxc=$lxc_
  		name_upgrading=
  		name_rootfs=
-@@ -195,24 +184,20 @@ set_vars(){
+@@ -195,24 +183,20 @@ set_vars(){
  		name_lxc="${lxc_}_new"
  		name_upgrading=$lxc_
  		name_rootfs="rootfs-${lxc_}"
@@ -141,7 +151,7 @@ index 9d5fc69..84cbc24 100755
  		path_work=$path_
  	else
  		path_work=$path_def
-@@ -223,17 +208,14 @@ set_vars(){
+@@ -223,17 +207,14 @@ set_vars(){
  	path_lxc_prepare=$path_cache/rootfs-$lxc_
  
  
@@ -162,7 +172,7 @@ index 9d5fc69..84cbc24 100755
  			printf $"Directory '%s' is not found.\n" $path_work >&2
  			exit 1
  		fi
-@@ -241,8 +223,7 @@ set_vars(){
+@@ -241,8 +222,7 @@ set_vars(){
  
  	type_fs=$(df -Th $path_work | awk 'NR==2 {print $2}')
  
@@ -172,7 +182,7 @@ index 9d5fc69..84cbc24 100755
  		# Считаем номер текущего корня обновляемой системы и определим новый
  		num_cur=$(grep lxc.rootfs.path $path_work/$lxc_/config | sed 's/.*rootfs//')
  		num_next=$(ls -d $path_work/$lxc_/rootfs* | sed 's/.*rootfs//' | sort -n | tail -n 1)
-@@ -255,10 +236,8 @@ set_vars(){
+@@ -255,10 +235,8 @@ set_vars(){
  	# taiga/amd64/20 -> taiga
  	lxc_profile=${profile_%%/*}
  
@@ -185,7 +195,7 @@ index 9d5fc69..84cbc24 100755
  			lxc_profile=$(file $path_work/$lxc_/rootfs$num_cur/etc/portage/make.profile | \
  				awk -F '/profiles/' '{ print $2 }' | awk -F '/' '{ print $1 }')
  			# совместимость со старыми системами
-@@ -316,27 +295,22 @@ launch_message(){
+@@ -316,27 +294,22 @@ launch_message(){
  
  check_vars(){
  	program_name=${0##*/}
@@ -218,7 +228,7 @@ index 9d5fc69..84cbc24 100755
  			param_name='--prepare'
  		fi
  		printf $"Wrong parameter %s, container '%s' does not exist!\n" $param_name $name_upgrading >&2
-@@ -349,20 +323,16 @@ check_vars(){
+@@ -349,20 +322,16 @@ check_vars(){
  			--prepare >&2
  		exit 1
  	fi
@@ -243,7 +253,7 @@ index 9d5fc69..84cbc24 100755
  			printf $"No operation specified. Call %s to update the container.\n" \
  				"'$program_name -u $name_lxc'" >&2
  			exit 1
-@@ -371,8 +341,7 @@ check_vars(){
+@@ -371,8 +340,7 @@ check_vars(){
  			exit 1
  		fi
  	fi
@@ -253,7 +263,7 @@ index 9d5fc69..84cbc24 100755
  		printf $"lxc.lxcpath must contain the path to  '/var/calculate/lxc'.\n" >&2
  		exit 1
  	fi
-@@ -383,10 +352,8 @@ create_base(){
+@@ -383,33 +351,30 @@ create_base(){
  	ebegin $"Downloading Calculate Linux"
  
  	# Создадим подтом, чтобы контейнер не участвовал в бэкапе btrbk
@@ -266,7 +276,23 @@ index 9d5fc69..84cbc24 100755
  			btrfs subvolume create $path_cache &>/dev/null
  		else
  			mkdir $path_cache
-@@ -408,8 +375,7 @@ create_base(){
+ 		fi
+ 	fi
+-
++	trap "rm -rf $path_def/scratch" SIGINT
+ 	lxc-create -n scratch -t download -- --server $mirror_ \
+ 			--arch x86_64 --dist scratch --release live \
+ 			2>>/var/log/calculate/cl-lxc-error.log >/dev/null || {
+ 		eend $? || true
+ 		eerror $"Failed to run lxc-create" >&2
+-		rm -rf $path_def/scratch
+ 		exit $?
+ 	}
+ 	eend
++	trap - SIGINT
+ 	mv $path_def/scratch $path_cache/scratch
+ 	true
+ }
  
  create_lxc(){
  	echo $"Creating container $name_lxc"
@@ -276,7 +302,7 @@ index 9d5fc69..84cbc24 100755
  		btrfs subvolume create $path_lxc >/dev/null || {
  			eend $? || true
  			eerror $"Failed to create subvolume $path_lxc" >&2
-@@ -421,8 +387,7 @@ create_lxc(){
+@@ -421,8 +386,7 @@ create_lxc(){
  	chmod 700 $path_lxc
  
  	local reflink='' && [ $type_fs = 'btrfs' ] && reflink='--reflink'
@@ -286,7 +312,7 @@ index 9d5fc69..84cbc24 100755
  		ebegin $"Restoring rootfs image from cache"
  		cp -a $reflink $path_lxc_prepare $path_lxc/rootfs
  		eend
-@@ -432,8 +397,7 @@ create_lxc(){
+@@ -432,8 +396,7 @@ create_lxc(){
  		eend
  	fi
  
@@ -296,7 +322,7 @@ index 9d5fc69..84cbc24 100755
  		ln -s $path_lxc $path_def/$name_lxc
  	fi
  
-@@ -446,8 +410,7 @@ create_lxc(){
+@@ -446,8 +409,7 @@ create_lxc(){
  			var/db/repos/gentoo
  	do
  		path_res=${path_lxc}/rootfs/${path_res}
@@ -306,7 +332,7 @@ index 9d5fc69..84cbc24 100755
  			rm -rf $path_res
  			mkdir $path_res
  		fi
-@@ -455,8 +418,7 @@ create_lxc(){
+@@ -455,13 +417,12 @@ create_lxc(){
  	eend
  
  	local calculate_mount= calculate_dir=
@@ -316,7 +342,13 @@ index 9d5fc69..84cbc24 100755
  		ebegin $"Moving /var/calculate to a separate mount point"
  		# Очистка и создание пути для монтирования ресурсов из хостовой машины
  		mv $path_lxc/rootfs/var/calculate $path_lxc
-@@ -469,48 +431,50 @@ create_lxc(){
+ 		mkdir $path_lxc/rootfs/var/calculate
+-		calculate_mount="lxc.mount.entry = ${path_lxc}/calculate var/calculate none rw,bind 0 0"$'\n'
++		calculate_mount="lxc.mount.entry = ${path_lxc}/calculate var/calculate none rw,bind 0 0"
+ 		calculate_dir="${path_lxc}/calculate"
+ 		eend
+ 	else
+@@ -469,48 +430,50 @@ create_lxc(){
  	fi
  
  	local portage_mount= gentoo_from= gentoo_to=
@@ -345,7 +377,7 @@ index 9d5fc69..84cbc24 100755
 -		then
 -			local repo_container='https://github.com/calculatelinux/container'
 +	if [[ ! -e /var/db/repos/container ]]; then
-+		container_mount="lxc.mount.entry = /var/calculate/repos/container var/db/repos/container none ro,bind 0 0"$'\n'
++		container_mount="lxc.mount.entry = /var/calculate/repos/container var/db/repos/container none ro,bind 0 0"
 +		if [[ -e /var/calculate/repos/container ]]; then
 +			rm -rf ${path_lxc}/rootfs/var/db/repos/container
  		else
@@ -376,7 +408,7 @@ index 9d5fc69..84cbc24 100755
 -		EOF
  	else
 +		# для совместимости с предыдушими установками
-+		container_mount="lxc.mount.entry = /var/db/repos/calculate var/db/repos/container none ro,bind 0 0"$'\n'
++		container_mount="lxc.mount.entry = /var/db/repos/container var/db/repos/container none ro,bind 0 0"
  		rm -rf ${path_lxc}/rootfs/var/db/repos/container
 -		mkdir ${path_lxc}/rootfs/var/db/repos/container
  	fi
@@ -391,7 +423,7 @@ index 9d5fc69..84cbc24 100755
  		net_conf=none
  		network_conf="lxc.net.0.type = none"
  		cp /etc/resolv.conf $path_lxc/rootfs/etc
-@@ -520,8 +484,7 @@ create_lxc(){
+@@ -520,8 +483,7 @@ create_lxc(){
  		local random_mac=$(printf '06:%02X:%02X:%02X:%02X:%02X\n' \
  			$((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256)))
  		local veth_pair="lxc.net.0.veth.pair = lxc-${name_lxc::11}"
@@ -401,18 +433,20 @@ index 9d5fc69..84cbc24 100755
  			# исключим настройку сетевого имени, если такое уже используется
  			veth_pair="#${veth_pair}"
  		fi
-@@ -554,9 +517,8 @@ create_lxc(){
+@@ -554,9 +516,10 @@ create_lxc(){
  	${network_conf}
  
  	# Mount points
 -	${calculate_mount}${portage_mount}
-+	${container_mount}${calculate_mount}${portage_mount}
++	${calculate_mount}
++	${container_mount}
  	lxc.mount.entry = /var/db/repos/calculate var/db/repos/calculate none ro,bind 0 0
 -	lxc.mount.entry = /var/db/repos/container var/db/repos/container none ro,bind 0 0
++	${portage_mount}
  	lxc.mount.entry = /var/cache/edb/binhost var/cache/edb/binhost none ro,bind 0 0
  	lxc.mount.entry = /var/calculate/packages var/calculate/packages none rw,bind 0 0
  	lxc.mount.entry = /var/calculate/distfiles var/calculate/distfiles none rw,bind 0 0
-@@ -595,8 +557,7 @@ create_lxc(){
+@@ -595,8 +558,7 @@ create_lxc(){
  	cat <<- EOF > ${calculate_dir}/templates/default/.calculate_directory
  	# Calculate env=install ac_install_live==on append=skip
  	EOF
@@ -422,7 +456,7 @@ index 9d5fc69..84cbc24 100755
  		cat <<- EOF > ${calculate_dir}/templates/default/runlevel.eth0
  		# Calculate mergepkg(sys-apps/openrc)!= path=/etc/runlevels/default name=net.eth0 protected link=/etc/init.d/net.lo symbolic
  		EOF
-@@ -607,8 +568,7 @@ create_lxc(){
+@@ -607,8 +569,7 @@ create_lxc(){
  	EOF
  	eend
  
@@ -432,17 +466,30 @@ index 9d5fc69..84cbc24 100755
  		launch_message
  	fi
  }
-@@ -659,8 +619,7 @@ update_prepare(){
+@@ -617,8 +578,7 @@ start_container(){
+ 	ebegin $"Starting container"
+ 	lxc-start $name_lxc
+ 	# ожидание первоначальной настройки контейнера
+-	while ! lxc-attach $name_lxc -- ps ax | grep 'init \[3\]' > /dev/null
+-	do
++	while ! lxc-attach $name_lxc -- ps ax | grep 'init \[3\]' > /dev/null; do
+ 		sleep 0.1
+ 	done
+ 	eend
+@@ -657,10 +617,8 @@ update_prepare(){
+ 	eend
+ 
  	ebegin $"Creating mount points"
- 	for mount_point in $(grep '^lxc.mount.entry' $path_work/$name_upgrading/config | awk {'print $4'})
- 	do
+-	for mount_point in $(grep '^lxc.mount.entry' $path_work/$name_upgrading/config | awk {'print $4'})
+-	do
 -		if [ ! -e "$path_lxc/rootfs/$mount_point" ]
 -		then
++	for mount_point in $(grep '^lxc.mount.entry' $path_work/$name_upgrading/config | awk {'print $4'}); do
 +		if [ ! -e "$path_lxc/rootfs/$mount_point" ]; then
  			mkdir -p "$path_lxc/rootfs/$mount_point"
  		fi
  	done
-@@ -674,8 +633,7 @@ update_prepare(){
+@@ -674,8 +632,7 @@ update_prepare(){
  	chmod 755 $path_lxc/rootfs/etc/local.d/firststart.start
  
  	# если обновляемый контейнер ни разу не запускался, возьем временный конфиг
@@ -452,7 +499,7 @@ index 9d5fc69..84cbc24 100755
  		cp ${path_work}/${name_upgrading}/rootfs${num_cur}/etc/calculate/calculate.env \
  			$path_lxc/rootfs/etc/calculate
  	else
-@@ -722,19 +680,16 @@ update_prepare(){
+@@ -722,19 +679,16 @@ update_prepare(){
  	eend
  
  	ebegin $"Saving image for update"
@@ -475,7 +522,7 @@ index 9d5fc69..84cbc24 100755
  			rm $path_def/$name_lxc # удалим символическую ссылку
  		fi
  	else
-@@ -754,8 +709,7 @@ upgrade_lxc(){
+@@ -754,8 +708,7 @@ upgrade_lxc(){
  
  	ebegin $"Moving image to $name_upgrading/rootfs$num_next"
  	local reflink=
@@ -485,7 +532,7 @@ index 9d5fc69..84cbc24 100755
  		reflink='--reflink'
  	fi
  	cp -a $reflink $path_lxc_prepare $path_work/$name_upgrading/rootfs$num_next
-@@ -791,15 +745,13 @@ upgrade_lxc(){
+@@ -791,15 +744,13 @@ upgrade_lxc(){
  		$path_work/$name_upgrading/config
  	eend
  
@@ -503,7 +550,15 @@ index 9d5fc69..84cbc24 100755
  		einfo $"Launching container $name_upgrading"
  		lxc-start $name_upgrading
  		eend
-@@ -813,8 +765,7 @@ upgrade_lxc(){
+@@ -807,14 +758,13 @@ upgrade_lxc(){
+ 
+ 	[ $diff_ == 1 ] && diff_pkg # Отобразим разницу в пакетах
+ 
+-	while ! (test -a $path_work/$name_upgrading/rootfs$num_next/etc/resolv.conf)
+-		do sleep 0.1
++	while ! (test -a $path_work/$name_upgrading/rootfs$num_next/etc/resolv.conf); do
++		sleep 0.1
+ 	done
  	einfo $(lxc-info -i $name_upgrading)
  
  	printf $"Container updated."
@@ -513,12 +568,15 @@ index 9d5fc69..84cbc24 100755
  		printf ' '
  		printf $"To start it, please run 'lxc-start %s'.\n" $name_upgrading
  	else
-@@ -835,14 +786,12 @@ diff_pkg(){
+@@ -833,16 +783,13 @@ diff_pkg(){
+ 	find $path_lxc_prepare/var/db/pkg/ -type d | sed 's/.*db\/pkg\///' | grep \/ | sort > $lock/new
+ 	cp $lock/new $lock/work
  
- 	while IFS= read -r pkg
- 	do
+-	while IFS= read -r pkg
+-	do
 -		if grep -q $pkg$ $lock/cur
 -		then
++	while IFS= read -r pkg; do
 +		if grep -q $pkg$ $lock/cur; then
  			sed -i "/$pkg/d" $lock/new
  			sed -i "/$pkg/d" $lock/cur
@@ -530,7 +588,7 @@ index 9d5fc69..84cbc24 100755
  		einfo $"No difference detected"
  	else
  		diff $lock/new $lock/cur || true
-@@ -855,10 +804,8 @@ clear_cache(){
+@@ -855,31 +802,24 @@ clear_cache(){
  	ebegin $"Clearing cache"
  	rm -rf /var/cache/lxc/download/*
  
@@ -543,12 +601,14 @@ index 9d5fc69..84cbc24 100755
  			btrfs subvolume delete /var/calculate/lxc/.cache > /dev/null
  		else
  			rm -rf /var/calculate/lxc/.cache
-@@ -867,19 +814,15 @@ clear_cache(){
+ 		fi
+ 	fi
  
- 	for i in /var/calculate/lxc/*
- 	do
+-	for i in /var/calculate/lxc/*
+-	do
 -		if [[ $i == /var/calulate/lxc/* ]]
 -		then
++	for i in /var/calculate/lxc/*; do
 +		if [[ $i == /var/calulate/lxc/* ]]; then
  			break
  		fi
@@ -567,7 +627,7 @@ index 9d5fc69..84cbc24 100755
  					btrfs subvolume delete $cache_dir/.cache > /dev/null
  				else
  					rm -rf $cache_dir/.cache
-@@ -911,39 +854,33 @@ check_vars
+@@ -911,39 +851,33 @@ check_vars
  
  # Чистка кэша
  # пустой файл partial когда lxc-create был прерван
