sys-apps/calculate-utils: обновление
* добавлена возможность прерывать сборку пакета при неподходящем патче в
шаблонах

diff --git a/profiles/templates/3.6/2_ac_install_merge/sys-apps/calculate-utils/profile.bashrc.d/50-patch-package b/profiles/templates/3.6/2_ac_install_merge/sys-apps/calculate-utils/profile.bashrc.d/50-patch-package
--- a/profiles/templates/3.6/2_ac_install_merge/sys-apps/calculate-utils/profile.bashrc.d/50-patch-package
+++ b/profiles/templates/3.6/2_ac_install_merge/sys-apps/calculate-utils/profile.bashrc.d/50-patch-package
@@ -19,5 +19,12 @@ if [[ ${EBUILD_PHASE} == "compile" ]] && [[ -d ${S} ]] && check_skip; then
 		[ -f ${CL_CORE_PATCH} ] && ${CL_CORE_PATCH} --no-progress --pkg-version ${PVR} \
 			--pkg-slot ${SLOT/\/*} --pkg-category ${CATEGORY} \
 			--pkg-path ${S} --pkg-name ${PN} --verbose
+		if [[ $? -eq 2 ]]
+		then
+			if /usr/libexec/calculate/cl-variable --value main.cl_template_wrong_patch | grep break &>/dev/null
+			then
+				die "Failed to apply Calculate utilities patch"
+			fi
+		fi
 	fi
 fi
